version: '3'
services: 
  nginx:
    build:
      dockerfile: ./caminho/do/dockerfile
      context: .
    image: mayara/nginx
    container_name: ngix
    ports: 
      - "80:80"
    networks: production-network
    depends_on: 
      - "node1"

    mongodb:
      image: mongo
      networks: production-network
    
    node1: 
      build: 
        dockerfile: ./caminho/do/dockerfile
        context: .
      image: mayara/node1
      container_name: mongo-db
      ports:
        - "3000"
      networks: production-network 
      depends_on: 
        - "mongodb"

networks: 
  production-network:
    driver: bridge
